/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Class.utils.Auth;
import RMIConnections.Client;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUN WEI
 */
public class CustomerCartForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCartForm
     */
    public CustomerCartForm() {
        initComponents();
        refresh();
        initialisedDocumentListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ContinueOrderingLabel = new javax.swing.JLabel();
        YourShoppingCartLabel = new javax.swing.JLabel();
        searchItemTextField = new javax.swing.JTextField();
        RemoveOrderButton = new javax.swing.JButton();
        OrderCheckoutButton = new javax.swing.JButton();
        editOrderButton = new javax.swing.JButton();
        orderTotalPriceTextField = new javax.swing.JTextField();
        ItemTotalPriceTextField = new javax.swing.JTextField();
        ItemNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ItemQuantitySpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        HomeLabel = new javax.swing.JLabel();
        CartLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        searchOrderItemLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ItemPriceTextField = new javax.swing.JTextField();
        refreshLabel = new javax.swing.JLabel();
        logOutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        ContinueOrderingLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContinueOrderingLabel.setText("Continue Ordering");
        ContinueOrderingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinueOrderingLabelMouseClicked(evt);
            }
        });

        YourShoppingCartLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        YourShoppingCartLabel.setText("Your Shopping Cart");

        searchItemTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchItemTextField.setText("Search Item");
        searchItemTextField.setToolTipText("Enter An Item Name");
        searchItemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemTextFieldActionPerformed(evt);
            }
        });

        RemoveOrderButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveOrderButton.setText("Remove Order");
        RemoveOrderButton.setToolTipText("Press Button To Remove Order");
        RemoveOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveOrderButtonMouseClicked(evt);
            }
        });
        RemoveOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveOrderButtonActionPerformed(evt);
            }
        });

        OrderCheckoutButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrderCheckoutButton.setText("Checkout");
        OrderCheckoutButton.setToolTipText("Press Button To Checkout");
        OrderCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderCheckoutButtonActionPerformed(evt);
            }
        });

        editOrderButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editOrderButton.setText("Edit Order");
        editOrderButton.setToolTipText("Press Button To Edit Order");
        editOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editOrderButtonMouseClicked(evt);
            }
        });
        editOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrderButtonActionPerformed(evt);
            }
        });

        orderTotalPriceTextField.setToolTipText("Display's Order Total Price");

        ItemTotalPriceTextField.setToolTipText("Display's Item Total Price");

        ItemNameTextField.setToolTipText("Display's Item Name");

        jLabel4.setText("Item Name:");

        jLabel5.setText("Item Quantity:");

        ItemQuantitySpinner.setToolTipText("Display's Item Quantity");
        ItemQuantitySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ItemQuantitySpinnerStateChanged(evt);
            }
        });

        jLabel6.setText("Item Total:");

        jLabel7.setText("Subtotal:");

        HomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        CartLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CartLabel.setText("Cart");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price Per Unit", "Order Quantity", "Item Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cartTable);
        if (cartTable.getColumnModel().getColumnCount() > 0) {
            cartTable.getColumnModel().getColumn(0).setResizable(false);
            cartTable.getColumnModel().getColumn(1).setResizable(false);
            cartTable.getColumnModel().getColumn(2).setResizable(false);
            cartTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchOrderItemLabel.setText("Search");
        searchOrderItemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchOrderItemLabelMouseClicked(evt);
            }
        });

        jLabel1.setText("Item Price:");

        ItemPriceTextField.setToolTipText("Display's Item Name");

        refreshLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshLabel.setText("refresh");
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        logOutLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logOutLabel.setText("Logout");
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(editOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(RemoveOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemQuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderTotalPriceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemTotalPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 85, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(OrderCheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 118, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(YourShoppingCartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ContinueOrderingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(logOutLabel)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchOrderItemLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshLabel)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContinueOrderingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(YourShoppingCartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchOrderItemLabel)
                    .addComponent(refreshLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ItemTotalPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(ItemQuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ItemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderTotalPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrderCheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchItemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchItemTextFieldActionPerformed

    private void OrderCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderCheckoutButtonActionPerformed
        try {
            Client.Object.viewOrder("2");
            new PaymentForm().setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(CustomerCartForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OrderCheckoutButtonActionPerformed

    private void editOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editOrderButtonActionPerformed

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        int selectedItemRowIndex = cartTable.getSelectedRow();
        
        ItemNameTextField.setText(model.getValueAt(selectedItemRowIndex, 0).toString());
        ItemPriceTextField.setText(model.getValueAt(selectedItemRowIndex, 1).toString());
        ItemTotalPriceTextField.setText(model.getValueAt(selectedItemRowIndex, 3).toString());
        ItemQuantitySpinner.setValue(model.getValueAt(selectedItemRowIndex, 2));
    }//GEN-LAST:event_cartTableMouseClicked

    private void ItemQuantitySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ItemQuantitySpinnerStateChanged
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        double itemPricePerUnit = Double.parseDouble(ItemPriceTextField.getText());
        Integer itemQuantity = (Integer)ItemQuantitySpinner.getValue();
        
        if(itemQuantity<0){
            JOptionPane.showMessageDialog(null, "Invalid quantity! Please try again");
            ItemQuantitySpinner.setValue(0);
        }
        else{
            double itemTotalPrice = itemPricePerUnit*itemQuantity;
            ItemTotalPriceTextField.setText(String.valueOf(itemTotalPrice));
        }
    }//GEN-LAST:event_ItemQuantitySpinnerStateChanged

    private void searchOrderItemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchOrderItemLabelMouseClicked
        // TODO add your handling code here:
        String searchItem = searchItemTextField.getText();
        try{
            if(Client.Object.searchCart(searchItem)){
                String searchedItem = Client.Object.getCartItem(searchItem);
                DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
                model.setRowCount(0);
                String[] splitSearchedItem = searchedItem.split(",");
                model.addRow(splitSearchedItem);
            }
            else{
                searchItemTextField.setText("Search Item");
                JOptionPane.showMessageDialog(null, searchItem+" not Found in cart! Please try again");
                
            }
        }catch(Exception ex) {
            Logger.getLogger(CustomerPlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchOrderItemLabelMouseClicked

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        // TODO add your handling code here:
        loadTable();
        refresh();
    }//GEN-LAST:event_refreshLabelMouseClicked

    private void RemoveOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveOrderButtonMouseClicked
        // TODO add your handling code here:
        String itemName = ItemNameTextField.getText();
        int itemQuantity = Integer.valueOf(ItemQuantitySpinner.getValue().toString());
        int customerID = 2;
        try{
            if(Client.Object.removeOrder(customerID, itemName, itemQuantity)){
                JOptionPane.showMessageDialog(null, itemName +" deleted from Order!");
                refresh();
            }else{
                JOptionPane.showMessageDialog(null, "Ordered item quantity not enough, please try again!");
            }
        }catch(Exception ex){
            Logger.getLogger(CustomerPlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RemoveOrderButtonMouseClicked

    private void editOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editOrderButtonMouseClicked
        // TODO add your handling code here:
        String itemName = ItemNameTextField.getText();
        int itemQuantity = Integer.valueOf(ItemQuantitySpinner.getValue().toString());
        int customerID = 2;
        try {
            if(Client.Object.updateCart(customerID, itemName, itemQuantity)){
                JOptionPane.showMessageDialog(null, "Item"+itemName+" updated Successfully!");
                refresh();
            }else{
               JOptionPane.showMessageDialog(null, "Item Quantity not available in inventory, item can't be updated!");
               
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerCartForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editOrderButtonMouseClicked

    private void ContinueOrderingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueOrderingLabelMouseClicked
        // TODO add your handling code here:
        new CustomerPlaceOrderForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_ContinueOrderingLabelMouseClicked

    private void RemoveOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveOrderButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RemoveOrderButtonActionPerformed

    private void logOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseClicked
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCartForm().setVisible(true);
            }
        });
    }
    
    private void loadTable() {
        try {
            String customerID = "2";
            DefaultTableModel model = Client.Object.viewCart(customerID);
            cartTable.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(CustomerPlaceOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refresh(){
        loadTable();
        editOrderButton.setEnabled(false);
        RemoveOrderButton.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        double totalOrderPrice = 0.0;
        double itemPrice = 0;
        for(int i=0; i<model.getRowCount(); i++){
            itemPrice = Double.valueOf(model.getValueAt(i, 3).toString());
            totalOrderPrice += itemPrice;
        }
        DecimalFormat df = new DecimalFormat("0.00");
        orderTotalPriceTextField.setText(String.format("%.2f",totalOrderPrice));
        ItemNameTextField.setText("");
        ItemQuantitySpinner.setValue(0);
        ItemPriceTextField.setText("");
        ItemTotalPriceTextField.setText("");
        searchItemTextField.setText("Search Item");
        
    }
    
    private void initialisedDocumentListener(){
        DocumentListener inputListener = new DocumentListener(){
            private void updateButtonState(){
                boolean itemSelected = Auth.textFieldsFilled(ItemNameTextField,ItemPriceTextField, ItemTotalPriceTextField); 
                System.out.println(itemSelected);
                editOrderButton.setEnabled(itemSelected);
                RemoveOrderButton.setEnabled(itemSelected);
            }
          
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateButtonState();            
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateButtonState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateButtonState();
            }
            
            
        };
        ItemNameTextField.getDocument().addDocumentListener(inputListener);
        ItemPriceTextField.getDocument().addDocumentListener(inputListener);
        ItemTotalPriceTextField.getDocument().addDocumentListener(inputListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CartLabel;
    private javax.swing.JLabel ContinueOrderingLabel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JTextField ItemNameTextField;
    private javax.swing.JTextField ItemPriceTextField;
    private javax.swing.JSpinner ItemQuantitySpinner;
    private javax.swing.JTextField ItemTotalPriceTextField;
    private javax.swing.JButton OrderCheckoutButton;
    private javax.swing.JButton RemoveOrderButton;
    private javax.swing.JLabel YourShoppingCartLabel;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton editOrderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JTextField orderTotalPriceTextField;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JTextField searchItemTextField;
    private javax.swing.JLabel searchOrderItemLabel;
    // End of variables declaration//GEN-END:variables
}
